name: Deploy to ACI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: 'Azure Container Registry Login'
        run: |
          az acr login --name xinye130containterregistry

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          name: myapp
          resource-group: GNG5300ResourceGroup
          dns-name-label: myapp${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:latest
          location: 'eastus'
          cpu: 1
          memory: 1.5
          ports: 80